# Generated by Django 3.1.6 on 2021-03-01 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qcwyinfo',
            old_name='city',
            new_name='yxkeywd',
        ),
    ]
