# Generated by Django 3.1.6 on 2021-03-01 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0003_cnkeywd_cskeywd_edkeywd_hykeywd_rtkeywd_wekeywd_wtkeywd_xckeywd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cnkeywd',
            old_name='cnkeywd',
            new_name='keywd',
        ),
        migrations.RenameField(
            model_name='cskeywd',
            old_name='cskeywd',
            new_name='keywd',
        ),
        migrations.RenameField(
            model_name='edkeywd',
            old_name='edkeywd',
            new_name='keywd',
        ),
        migrations.RenameField(
            model_name='hykeywd',
            old_name='hykeywd',
            new_name='keywd',
        ),
        migrations.RenameField(
            model_name='qcwyinfo',
            old_name='yxkeywd',
            new_name='keywd',
        ),
        migrations.RenameField(
            model_name='rtkeywd',
            old_name='rtkeywd',
            new_name='keywd',
        ),
        migrations.RenameField(
            model_name='wekeywd',
            old_name='wekeywd',
            new_name='keywd',
        ),
        migrations.RenameField(
            model_name='wtkeywd',
            old_name='wtkeywd',
            new_name='keywd',
        ),
        migrations.RenameField(
            model_name='xckeywd',
            old_name='xckeywd',
            new_name='keywd',
        ),
    ]
